### ISSUE TITLE
需要自己建数据库么，好像没看见数据库文件

### ISSUE THREAD

**Issue by github210609** [kentxxq/pusher#2]
需要自己建数据库么，好像没看见数据库文件？

**Comment by github210609** [comment]
应该是没有正确初始化：
2024-11-14 13:42:17.225 +08:00|INF|pusher.webapi.Jobs.DatabaseInit|ThreadName|15|开始任务DatabaseInit

2024-11-14 13:47:18.379 +08:00|ERR|Serilog.AspNetCore.RequestLoggingMiddleware|ThreadName|16|HTTP POST /pusher.webapi/User/Login responded 500 in 234.3035 msMicrosoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such table: User'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at SqlSugar.AdoProvider.GetDataReaderAsync(String sql, SugarParameter[] parameters)
   at SqlSugar.QueryableProvider`1.GetDataAsync[TResult](KeyValuePair`2 sqlObj)
   at SqlSugar.QueryableProvider`1._ToListAsync[TResult]()
   at SqlSugar.QueryableProvider`1.FirstAsync()
   at SqlSugar.QueryableProvider`1.FirstAsync(Expression`1 expression)
   at pusher.webapi.Service.UserService.Login(String username, String password) in /root/pusher/pusher.webapi/Service/UserService.cs:line 45
   at pusher.webapi.Controllers.UserController.Login(LoginRO loginRO) in /root/pusher/pusher.webapi/Controllers/UserController.cs:line 43
   at lambda_method11(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by kentxxq** [comment]
@github210609 会根据`appsettings.json`的配置创建数据库,我这边没问题. 目录是`pusher/pusher.webapi/demo.sqlite`

检测到demo.sqlite不存在,就会创建这个文件然后同步表结构.  
之后会创建初始用户`初始化ken用户成功`, 如果已经存在会记录`ken用户已存在,不插入新数据` .   User表不存在的情况我没有复现出来




```shell
2024-11-26 14:13:49.339 +08:00|INF|pusher.webapi.Jobs.DatabaseInit|ThreadName|11|开始任务DatabaseInit
2024-11-26 14:13:49.495 +08:00|INF|pusher.webapi.Service.Database.DBService|ThreadName|11|数据库demo.sqlite不存在
2024-11-26 14:13:49.583 +08:00|INF|pusher.webapi.Service.Database.DBService|ThreadName|11|开始同步表结构
建表...
2024-11-26 14:13:49.694 +08:00|INF|pusher.webapi.Service.Database.DBService|ThreadName|11|表结构同步完成
2024-11-26 14:13:49.788 +08:00|INF|pusher.webapi.Service.Database.DBService|ThreadName|11|初始化ken用户成功
```
